.pragma library

// GENERATED by scripts/gen-herdr-schema.mjs from tests/fixtures/herdr-*/. Do not edit;
// run `node scripts/gen-herdr-schema.mjs` after adding or recapturing a fixture.
//
// The herdr API names gjetr is tested against, per supported build: event and
// subscription names, every method, the params of the requests gjetr sends, the
// fields of the results and objects it reads, and the agent kinds herdr reports.
// Unknown fields and names stay tolerated at runtime; this is what each build
// promised, never what a newer one may add.

var SUPPORTED = [
  {
    "version": "0.8.2",
    "protocol": 20
  },
  {
    "version": "0.9.0",
    "protocol": 22
  }
]

var AGENT_KINDS = ["pi", "claude", "codex", "gemini", "cursor", "devin", "agy", "cline", "omp", "mastracode", "opencode", "copilot", "kimi", "kiro", "droid", "amp", "grok", "hermes", "kilo", "qodercli", "qwen", "maki", "muse"]

var VERSIONS = [
  {
    "version": "0.8.2",
    "protocol": 20,
    "schemaVersion": 1,
    "eventKinds": ["workspace_created", "workspace_updated", "workspace_metadata_updated", "workspace_closed", "workspace_renamed", "workspace_moved", "workspace_reordered", "workspace_focused", "worktree_created", "worktree_opened", "worktree_removed", "tab_created", "tab_closed", "tab_renamed", "tab_moved", "tab_focused", "pane_created", "pane_closed", "pane_updated", "pane_focused", "pane_moved", "pane_output_changed", "pane_exited", "pane_agent_detected", "pane_agent_status_changed", "layout_updated"],
    "eventFields": {
      "layout_updated": ["layout", "type"],
      "pane_agent_detected": ["agent", "final_status", "pane_id", "released", "type", "workspace_id"],
      "pane_agent_status_changed": ["agent", "agent_status", "display_agent", "pane_id", "state_labels", "title", "type", "workspace_id"],
      "pane_closed": ["pane_id", "type", "workspace_id"],
      "pane_created": ["pane", "type"],
      "pane_exited": ["pane_id", "type", "workspace_id"],
      "pane_focused": ["pane_id", "type", "workspace_id"],
      "pane_moved": ["closed_tab_id", "closed_workspace_id", "created_tab", "created_workspace", "pane", "previous_pane_id", "previous_tab_id", "previous_workspace_id", "type"],
      "pane_output_changed": ["pane_id", "revision", "type", "workspace_id"],
      "pane_updated": ["pane", "type"],
      "tab_closed": ["tab_id", "type", "workspace_id"],
      "tab_created": ["tab", "type"],
      "tab_focused": ["tab_id", "type", "workspace_id"],
      "tab_moved": ["insert_index", "tab_id", "tabs", "type", "workspace_id"],
      "tab_renamed": ["label", "tab_id", "type", "workspace_id"],
      "workspace_closed": ["type", "workspace", "workspace_id"],
      "workspace_created": ["type", "workspace"],
      "workspace_focused": ["type", "workspace_id"],
      "workspace_metadata_updated": ["type", "workspace"],
      "workspace_moved": ["insert_index", "type", "workspace_id", "workspaces"],
      "workspace_renamed": ["label", "type", "workspace_id"],
      "workspace_reordered": ["before_workspace_id", "type", "workspace_ids", "workspaces"],
      "workspace_updated": ["type", "workspace"],
      "worktree_created": ["type", "workspace", "worktree"],
      "worktree_opened": ["already_open", "type", "workspace", "worktree"],
      "worktree_removed": ["forced", "type", "workspace", "workspace_id", "worktree"]
    },
    "subscriptionTypes": ["workspace.created", "workspace.updated", "workspace.metadata_updated", "workspace.renamed", "workspace.moved", "workspace.reordered", "workspace.closed", "workspace.focused", "worktree.created", "worktree.opened", "worktree.removed", "tab.created", "tab.closed", "tab.focused", "tab.renamed", "tab.moved", "pane.created", "pane.closed", "pane.updated", "pane.focused", "pane.moved", "pane.exited", "pane.agent_detected", "pane.output_matched", "pane.agent_status_changed", "pane.scroll_changed", "layout.updated"],
    "methods": ["agent.explain", "agent.focus", "agent.get", "agent.list", "agent.prompt", "agent.read", "agent.rename", "agent.send_keys", "agent.start", "agent.view.clear", "agent.view.set", "agent.wait", "client.window_title.clear", "client.window_title.set", "events.subscribe", "events.wait", "integration.install", "integration.uninstall", "layout.apply", "layout.export", "layout.set_split_ratio", "notification.show", "pane.clear_agent_authority", "pane.close", "pane.current", "pane.edges", "pane.focus", "pane.focus_direction", "pane.get", "pane.graphics.clear", "pane.graphics.info", "pane.graphics.set", "pane.input.set", "pane.layout", "pane.list", "pane.move", "pane.neighbor", "pane.process_info", "pane.read", "pane.release_agent", "pane.rename", "pane.report_agent", "pane.report_agent_session", "pane.report_metadata", "pane.resize", "pane.send_input", "pane.send_keys", "pane.send_text", "pane.split", "pane.swap", "pane.wait_for_output", "pane.zoom", "ping", "plugin.action.invoke", "plugin.action.list", "plugin.disable", "plugin.enable", "plugin.link", "plugin.list", "plugin.log.list", "plugin.pane.close", "plugin.pane.focus", "plugin.pane.open", "plugin.unlink", "popup.close", "server.agent_manifests", "server.live_handoff", "server.reload_agent_manifests", "server.reload_config", "server.stop", "session.snapshot", "tab.close", "tab.create", "tab.focus", "tab.get", "tab.list", "tab.move", "tab.rename", "workspace.close", "workspace.create", "workspace.focus", "workspace.get", "workspace.list", "workspace.move", "workspace.move_block", "workspace.rename", "workspace.report_metadata", "worktree.create", "worktree.list", "worktree.open", "worktree.remove"],
    "requestParams": {
      "events.subscribe": {
        "properties": ["subscriptions"],
        "required": ["subscriptions"]
      },
      "pane.focus": {
        "properties": ["pane_id"],
        "required": ["pane_id"]
      },
      "ping": {
        "properties": [],
        "required": []
      },
      "session.snapshot": {
        "properties": [],
        "required": []
      },
      "tab.focus": {
        "properties": ["tab_id"],
        "required": ["tab_id"]
      },
      "workspace.focus": {
        "properties": ["workspace_id"],
        "required": ["workspace_id"]
      }
    },
    "resultFields": {
      "pong": ["capabilities", "protocol", "type", "version"],
      "session_snapshot": ["snapshot", "type"],
      "subscription_started": ["type"]
    },
    "fields": {
      "snapshot": ["agents", "focused_pane_id", "focused_tab_id", "focused_workspace_id", "layouts", "panes", "protocol", "tabs", "version", "workspaces"],
      "agent": ["agent", "agent_session", "agent_status", "cwd", "display_agent", "focused", "foreground_cwd", "interactive_ready", "launch_pending", "name", "pane_id", "revision", "screen_detection_skipped", "state_change_seq", "state_labels", "tab_id", "terminal_id", "terminal_title", "terminal_title_stripped", "title", "tokens", "workspace_id"],
      "pane": ["agent", "agent_session", "agent_status", "cwd", "display_agent", "focused", "foreground_cwd", "label", "pane_id", "revision", "scroll", "state_labels", "tab_id", "terminal_id", "terminal_title", "terminal_title_stripped", "title", "tokens", "workspace_id"],
      "tab": ["agent_status", "focused", "label", "number", "pane_count", "tab_id", "workspace_id"],
      "workspace": ["active_tab_id", "agent_status", "focused", "label", "number", "pane_count", "tab_count", "tokens", "workspace_id", "worktree"],
      "agentSession": ["agent", "kind", "source", "value"]
    },
    "agentStatuses": ["idle", "working", "blocked", "done", "unknown"],
    "integrationTargets": ["pi", "omp", "claude", "codex", "copilot", "devin", "droid", "kimi", "opencode", "kilo", "hermes", "qodercli", "qwen", "cursor", "mastracode", "antigravity_cli", "grok"],
    "agentKinds": ["pi", "claude", "codex", "gemini", "cursor", "devin", "agy", "cline", "omp", "mastracode", "opencode", "copilot", "kimi", "kiro", "droid", "amp", "grok", "hermes", "kilo", "qodercli", "qwen", "maki"]
  },
  {
    "version": "0.9.0",
    "protocol": 22,
    "schemaVersion": 1,
    "eventKinds": ["workspace_created", "workspace_updated", "workspace_metadata_updated", "workspace_closed", "workspace_renamed", "workspace_moved", "workspace_reordered", "workspace_focused", "worktree_created", "worktree_opened", "worktree_removed", "tab_created", "tab_closed", "tab_renamed", "tab_moved", "tab_focused", "pane_created", "pane_closed", "pane_updated", "pane_focused", "pane_moved", "pane_output_changed", "pane_exited", "pane_agent_detected", "pane_agent_status_changed", "layout_updated"],
    "eventFields": {
      "layout_updated": ["layout", "type"],
      "pane_agent_detected": ["agent", "final_status", "pane_id", "released", "type", "workspace_id"],
      "pane_agent_status_changed": ["agent", "agent_status", "display_agent", "pane_id", "state_labels", "title", "type", "workspace_id"],
      "pane_closed": ["pane_id", "type", "workspace_id"],
      "pane_created": ["pane", "type"],
      "pane_exited": ["pane_id", "type", "workspace_id"],
      "pane_focused": ["pane_id", "type", "workspace_id"],
      "pane_moved": ["closed_tab_id", "closed_workspace_id", "created_tab", "created_workspace", "pane", "previous_pane_id", "previous_tab_id", "previous_workspace_id", "type"],
      "pane_output_changed": ["pane_id", "revision", "type", "workspace_id"],
      "pane_updated": ["pane", "type"],
      "tab_closed": ["tab_id", "type", "workspace_id"],
      "tab_created": ["tab", "type"],
      "tab_focused": ["tab_id", "type", "workspace_id"],
      "tab_moved": ["insert_index", "tab_id", "tabs", "type", "workspace_id"],
      "tab_renamed": ["label", "tab_id", "type", "workspace_id"],
      "workspace_closed": ["type", "workspace", "workspace_id"],
      "workspace_created": ["type", "workspace"],
      "workspace_focused": ["type", "workspace_id"],
      "workspace_metadata_updated": ["type", "workspace"],
      "workspace_moved": ["insert_index", "type", "workspace_id", "workspaces"],
      "workspace_renamed": ["label", "type", "workspace_id"],
      "workspace_reordered": ["before_workspace_id", "type", "workspace_ids", "workspaces"],
      "workspace_updated": ["type", "workspace"],
      "worktree_created": ["type", "workspace", "worktree"],
      "worktree_opened": ["already_open", "type", "workspace", "worktree"],
      "worktree_removed": ["forced", "type", "workspace", "workspace_id", "worktree"]
    },
    "subscriptionTypes": ["workspace.created", "workspace.updated", "workspace.metadata_updated", "workspace.renamed", "workspace.moved", "workspace.reordered", "workspace.closed", "workspace.focused", "worktree.created", "worktree.opened", "worktree.removed", "tab.created", "tab.closed", "tab.focused", "tab.renamed", "tab.moved", "pane.created", "pane.closed", "pane.updated", "pane.focused", "pane.moved", "pane.exited", "pane.agent_detected", "pane.output_matched", "pane.agent_status_changed", "pane.scroll_changed", "layout.updated"],
    "methods": ["agent.explain", "agent.focus", "agent.get", "agent.list", "agent.prompt", "agent.read", "agent.rename", "agent.send_keys", "agent.start", "agent.view.clear", "agent.view.set", "agent.wait", "client.window_title.clear", "client.window_title.set", "client_shell.surface.set", "command.invoke", "events.subscribe", "events.wait", "integration.install", "integration.list", "integration.uninstall", "layout.apply", "layout.export", "layout.set_split_ratio", "notification.show", "pane.clear_agent_authority", "pane.close", "pane.copy_motion", "pane.copy_search", "pane.current", "pane.edges", "pane.edit_scrollback", "pane.focus", "pane.focus_direction", "pane.get", "pane.graphics.clear", "pane.graphics.info", "pane.graphics.set", "pane.input.set", "pane.layout", "pane.link.activate", "pane.list", "pane.move", "pane.neighbor", "pane.process_info", "pane.read", "pane.release_agent", "pane.rename", "pane.report_agent", "pane.report_agent_session", "pane.report_metadata", "pane.resize", "pane.scroll", "pane.selection.read", "pane.send_input", "pane.send_keys", "pane.send_text", "pane.split", "pane.swap", "pane.wait_for_output", "pane.zoom", "ping", "plugin.action.invoke", "plugin.action.list", "plugin.disable", "plugin.enable", "plugin.link", "plugin.list", "plugin.log.list", "plugin.pane.close", "plugin.pane.focus", "plugin.pane.open", "plugin.unlink", "popup.close", "product_announcement.dismiss", "release_notes.dismiss", "server.agent_manifests", "server.live_handoff", "server.reload_agent_manifests", "server.reload_config", "server.stop", "session.snapshot", "tab.close", "tab.create", "tab.focus", "tab.get", "tab.list", "tab.move", "tab.rename", "workspace.close", "workspace.create", "workspace.focus", "workspace.get", "workspace.list", "workspace.move", "workspace.move_block", "workspace.rename", "workspace.report_metadata", "worktree.create", "worktree.list", "worktree.open", "worktree.remove"],
    "requestParams": {
      "events.subscribe": {
        "properties": ["subscriptions"],
        "required": ["subscriptions"]
      },
      "pane.focus": {
        "properties": ["pane_id"],
        "required": ["pane_id"]
      },
      "ping": {
        "properties": [],
        "required": []
      },
      "session.snapshot": {
        "properties": [],
        "required": []
      },
      "tab.focus": {
        "properties": ["tab_id"],
        "required": ["tab_id"]
      },
      "workspace.focus": {
        "properties": ["workspace_id"],
        "required": ["workspace_id"]
      }
    },
    "resultFields": {
      "pong": ["capabilities", "protocol", "type", "version"],
      "session_snapshot": ["snapshot", "type"],
      "subscription_started": ["type"]
    },
    "fields": {
      "snapshot": ["agents", "focused_pane_id", "focused_tab_id", "focused_workspace_id", "layouts", "panes", "protocol", "tabs", "version", "workspaces"],
      "agent": ["agent", "agent_session", "agent_status", "cwd", "display_agent", "focused", "foreground_cwd", "interactive_ready", "launch_pending", "name", "pane_id", "revision", "screen_detection_skipped", "state_change_seq", "state_labels", "tab_id", "terminal_id", "terminal_title", "terminal_title_stripped", "title", "tokens", "workspace_id"],
      "pane": ["agent", "agent_session", "agent_status", "cwd", "display_agent", "focused", "foreground_cwd", "label", "pane_id", "revision", "scroll", "state_labels", "tab_id", "terminal_id", "terminal_title", "terminal_title_stripped", "title", "tokens", "workspace_id"],
      "tab": ["agent_status", "focused", "label", "number", "pane_count", "tab_id", "workspace_id"],
      "workspace": ["active_tab_id", "agent_status", "focused", "label", "number", "pane_count", "tab_count", "tokens", "workspace_id", "worktree"],
      "agentSession": ["agent", "kind", "source", "value"]
    },
    "agentStatuses": ["idle", "working", "blocked", "done", "unknown"],
    "integrationTargets": ["pi", "omp", "claude", "codex", "copilot", "devin", "droid", "kimi", "opencode", "kilo", "hermes", "qodercli", "qwen", "cursor", "mastracode", "antigravity_cli", "grok"],
    "agentKinds": ["pi", "claude", "codex", "gemini", "cursor", "devin", "agy", "cline", "omp", "mastracode", "opencode", "copilot", "kimi", "kiro", "droid", "amp", "grok", "hermes", "kilo", "qodercli", "qwen", "maki", "muse"]
  }
]

if (typeof module !== "undefined") {
  module.exports = {
    SUPPORTED: SUPPORTED,
    AGENT_KINDS: AGENT_KINDS,
    VERSIONS: VERSIONS
  }
}
